Algoritmo "semnome"
//Crie um programa que leia o nome, aniversario e e-mail do usuario, no final exibir essas informações conforme abaixo:



//Nome: Cristiano
//Aniversário: 12 de junho
//E-mail: cristianoaj@gmail.com
Var
nome, niver, email:caracter


Inicio
escreva("digite seu nome:")
leia (nome)
escreva("digite seu aniversário:")
leia(niver)
escreva("digite seu e-mail:")
leia (email)

escreval("nome: ",nome)

escreval("niver: ",niver)
escreval("email: ",email)
Fimalgoritmo